[package]
name = "affinitypool"
edition = "2021"
version = "0.1.3"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "A Rust library for running blocking jobs on a dedicated thread pool with CPU core affinity"
repository = "https://github.com/surrealdb/affinitypool"
homepage = "https://github.com/surrealdb/affinitypool"
documentation = "https://docs.rs/affinitypool/"
keywords = ["pool", "parallelism", "threading", "thread", "threadpool"]
categories = ["asynchronous", "concurrency", "os"]
resolver = "2"

[features]
default = []

[dependencies]
async-channel = "2.3.1"
num_cpus = "1.16.0"
thiserror = "1.0.63"
tokio = { version = "1.42.0", features = ["sync"] }
