[package]
name = "affinitypool"
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"
readme = "README.md"

[features]
default = []

[dependencies]
async-channel = "2.3.1"
num_cpus = "1.16.0"
thiserror = "1.0.63"
tokio = { version = "1.42.0", features = ["sync"] }
